server:
  port: 8002
spring:
  application:
    name: userService
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: false
        serviceName: userService
        health-check-path: /actuator/health
        health-check-interval: 10s
        register: false
  flyway:
    enabled: false
  redis:
    host: www.fan2wan.top
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 10
        max-wait: 2000

feign:
  hystrix:
    enabled: true

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://www.fan2wan.top:7777/testSpring?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fant
    password: 123456
  flyway:
    locations: classpath:/db/mysql
    baseline-on-migrate: true