server:
  port: 8001

spring:
  application:
    name: orderService
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: orderService
        health-check-path: /actuator/health #引入actuator 配置健康检查路径 也可以自定义url 返回ok
        health-check-interval: 10s
        register: false
        enabled: false
  profiles:
    active: dev
  flyway:
    enabled: false

feign:
  hystrix:
    enabled: true
#      feign 重试机制
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
hystrix:
  threadpool: # 接口限流 这个配置只在hystrix THREAD 模式下才有用
#    userService: #可以给单独某个feign 客户端配置 甚至可以给指定方法配置
#      coreSize: 2
#      maxQueueSize: 5
#      queueSizeRejectionThreshold: 3
    default:  #默认配置
      coreSize: 2
      maxQueueSize: 5
      queueSizeRejectionThreshold: 3
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000
          strategy: THREAD

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://www.fan2wan.top:7777/testSpring?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fant
    password: 123456
  flyway:
    locations: classpath:/db/mysql
#    baseline-on-migrate: true