server:
  port: 9001

spring:
  application:
    name: zuul-service
#  profiles:
#    active: dev
  cloud:
    consul:
      host: 192.168.5.68
      port: 8500
      discovery:
        serviceName: zuul-service
        health-check-path: /actuator/health
        health-check-interval: 10s
        enabled: false
        register: false
#zuul:
#  routes:
#    order-service:  /order/**